const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Flash,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{cenarioUm: 0},
	{Sólido: 0},
	{plataformaUm: 0},
	{Fixar: 0},
	{CentrarEm: 0},
	{papaiNoel: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{jogador: 0},
	{Teclado: 0},
	{Senóide: 0},
	{presenteUmAzul: 0},
	{presenteDoisAzul: 0},
	{Âncora: 0},
	{Texto: 0},
	{marcador: 0},
	{BannerInicio: 0},
	{Mouse: 0},
	{botaoJogar: 0},
	{gameOver: 0},
	{acao: 0},
	{inimigo1: 0},
	{chave: 0},
	{vitoria: 0},
	{casa: 0},
	{arvore: 0},
	{sapatinho: 0},
	{seta: 0},
	{bolinhas: 0},
	{treno: 0},
	{Sprite2: 0},
	{decoracaoPresente: 0},
	{luzes: 0},
	{Áudio: 0},
	{Piscar: 0},
	{Girar: 0},
	{neve: 0},
	{pontos: 0}
];

self.InstanceType = {
	cenarioUm: class extends self.ITiledBackgroundInstance {},
	plataformaUm: class extends self.ITiledBackgroundInstance {},
	papaiNoel: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	presenteUmAzul: class extends self.ISpriteInstance {},
	presenteDoisAzul: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	marcador: class extends self.ISpriteInstance {},
	BannerInicio: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	botaoJogar: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	chave: class extends self.ISpriteInstance {},
	vitoria: class extends self.ISpriteInstance {},
	casa: class extends self.ISpriteInstance {},
	arvore: class extends self.ISpriteInstance {},
	sapatinho: class extends self.ISpriteInstance {},
	seta: class extends self.ISpriteInstance {},
	bolinhas: class extends self.ISpriteInstance {},
	treno: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	decoracaoPresente: class extends self.ISpriteInstance {},
	luzes: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	neve: class extends self.ISpriteInstance {}
}